services:
  frontend:
    build:
      context: ./frontend  # Points to the frontend directory
      dockerfile: Dockerfile  # This should point to the frontend Dockerfile
    container_name: starteryou-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"  # Exposes frontend on port 8080
    environment:
      - BACKEND_URL=http://54.196.202.145:3000  # Set the backend URL, adjust as needed
    networks:
      - starteryou-network

networks:
  starteryou-network:
    driver: bridge
